name: build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'
      - run: go test -v ./...
